name: Release
on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7
    permissions:
      contents: write
    with:
      release_files: mbo_bzl-*.tar.gz
      prerelease: true
