name: Release
on:
  push:
    tags:
      # trunk-ignore(yamllint/quoted-strings)
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse Version
        id: version
        run: |
          TAG_NAME=${{ github.ref_name }}
          CLEAN_VERSION=${TAG_NAME#v}
          echo "clean_version=${CLEAN_VERSION}" >> $GITHUB_OUTPUT

      # Instead of the reusable workflow, we call the release action directly
      # This allows us to customize the tag vs the release name perfectly.
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.version.outputs.clean_version }}
          tag_name: ${{ github.ref_name }}
          files: bzl-*.tar.gz
          prerelease: true
