name: Release
on:
  push:
    tags:
      # trunk-ignore(yamllint/quoted-strings)
      - "v*.*.*"

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7
    permissions:
      id-token: write       # Required to verify build provenance via OIDC
      attestations: write   # Required to sign release artifacts securely
      contents: write       # Required to create the release and upload bzl-*.tar.gz
    with:
      release_files: bzl-*.tar.gz
      prerelease: true
